apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-8"
  annotations:
    argocd/app-name: my-quarkus-app-8-dev
    backstage.io/kubernetes-id: my-quarkus-app-8
    github.com/project-slug: janus-demo-video/my-quarkus-app-8
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-964vw.964vw.sandbox2901.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-8?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: CodeReady Workspaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-964vw.964vw.sandbox2901.opentlc.com/#https://github.com/janus-demo-video/my-quarkus-app-8?che-editor=che-incubator/che-idea/next&devfilePath=.devfile-intellij.yaml
      title: CodeReady Workspaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "mattheh"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: artist-api
  description: Retrieve artist details
spec:
  type: openapi
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  definition:
    $text: ./openapi.yaml
